services:
  nginx:
    image: nginx:alpine
    container_name: moodle-nginx-dev
    ports:
      - "8080:80"
    volumes:
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./config/nginx/moodle.conf:/etc/nginx/conf.d/default.conf:ro
      - moodle-code:/var/www/html   #  named volume untuk windows environment
    depends_on:
       moodleapp:
         condition: service_healthy
    networks:
      - moodle-dev-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://127.0.0.1/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  moodleapp:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
      args:
        ENVIRONMENT: development
    image: moodle-web-dev
    container_name: moodle-web-dev
    volumes:
      - ./data/moodle_data-dev:/var/www/moodledata
      - moodle-code:/var/www/html   #  named volume untuk windows environment
      #- ./secrets/db_password.txt:/run/secrets/db_password:ro
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    #env_file: .env.dev
    environment:
      ENVIRONMENT: development
      RESTORE_ON_EMPTY_DB: "false"
      PGSQL_HOST: ${PGSQL_HOST}
      PGSQL_USER: ${PGSQL_USER}
      PGSQL_DATABASE: ${PGSQL_DATABASE}
      PGSQL_PASSWORD: ${PGSQL_PASSWORD}
      MOODLE_WWWROOT: ${MOODLE_WWWROOT}
      DEBUG: 'true'
    networks:
      - moodle-dev-network
    healthcheck:
      test: ["CMD-SHELL", "php-fpm -t 2>/dev/null || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  postgres:
    image: postgres:17-alpine
    container_name: moodle-pgdb-dev
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${PGSQL_DATABASE}
      POSTGRES_USER: ${PGSQL_USER}
      POSTGRES_PASSWORD: ${PGSQL_PASSWORD}
      #POSTGRES_PASSWORD_FILE: /run/secrets/db_password
    volumes:
      - pgdata-dev:/var/lib/postgresql/data
      #- ./secrets/db_password.txt:/run/secrets/db_password:ro
    networks:
      - moodle-dev-network
    healthcheck:
      test: ["CMD-SHELL","pg_isready -U ${PGSQL_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin-dev
    profiles:
    - dev
    ports:
      - "81:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    depends_on:
      - postgres
    networks:
      - moodle-dev-network
    restart: unless-stopped

  moodle-cron:
    image: moodle-web-dev
    container_name: moodle-cron.dev
    entrypoint: ["/bin/sh","-c","/opt/scripts/generate-config.sh && /opt/scripts/cron.sh && crond -f -l 8"]
    volumes:
      - ./data/moodle_data-dev:/var/www/moodledata
      - moodle-code:/var/www/html   #  named volume untuk windows environment
      #- ./secrets/db_password.txt:/run/secrets/db_password:ro
    environment:
      ENVIRONMENT: development
      PGSQL_HOST: ${PGSQL_HOST}
      PGSQL_USER: ${PGSQL_USER}
      PGSQL_DATABASE: ${PGSQL_DATABASE}
      PGSQL_PASSWORD: ${PGSQL_PASSWORD}
      #MOODLE_DATABASE_PASSWORD_FILE: /run/secrets/db_password
    networks:
      - moodle-dev-network
    restart: unless-stopped

volumes:
  pgdata-dev:
  moodledata-dev:
  moodle-code:      #  named volume untuk windows environment

networks:
  moodle-dev-network:
    driver: bridge
