                                                                                                                                                                                                                                                                                                                                                                                                                    #!/bin/bash
                                                                                                                                                                                                                                                                                                                                                                                                                    # filepath: /home/taufiqr/moodle-docker/scripts/notify-discord.sh
                                                                                                                                                                                                                                                                                                                                                                                                                    # Helper: kirim notifikasi ke Discord via webhook
                                                                                                                                                                                                                                                                                                                                                                                                                    # Usage: notify-discord.sh "<level>" "<title>" "<message>"
                                                                                                                                                                                                                                                                                                                                                                                                                    # Level: info | success | warning | error

                                                                                                                                                                                                                                                                                                                                                                                                                    LEVEL="${1:-info}"
                                                                                                                                                                                                                                                                                                                                                                                                                    TITLE="${2:-Moodle Notification}"
                                                                                                                                                                                                                                                                                                                                                                                                                    MESSAGE="${3:-No message}"
                                                                                                                                                                                                                                                                                                                                                                                                                    WEBHOOK_URL="${DISCORD_WEBHOOK_URL:-}"

                                                                                                                                                                                                                                                                                                                                                                                                                    # Jika tidak ada webhook URL, skip (tidak error)
                                                                                                                                                                                                                                                                                                                                                                                                                    [ -z "$WEBHOOK_URL" ] && exit 0

                                                                                                                                                                                                                                                                                                                                                                                                                    # Warna embed Discord berdasarkan level
                                                                                                                                                                                                                                                                                                                                                                                                                    case "$LEVEL" in
                                                                                                                                                                                                                                                                                                                                                                                                                        success) COLOR=3066993  ;; # hijau
                                                                                                                                                                                                                                                                                                                                                                                                                        warning) COLOR=16776960 ;; # kuning
                                                                                                                                                                                                                                                                                                                                                                                                                        error)   COLOR=15158332 ;; # merah
                                                                                                                                                                                                                                                                                                                                                                                                                        *)       COLOR=3447003  ;; # biru (info)
                                                                                                                                                                                                                                                                                                                                                                                                                    esac

                                                                                                                                                                                                                                                                                                                                                                                                                    HOSTNAME=$(hostname 2>/dev/null || echo "unknown")
                                                                                                                                                                                                                                                                                                                                                                                                                    TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
                                                                                                                                                                                                                                                                                                                                                                                                                    ENVIRONMENT="${ENVIRONMENT:-unknown}"

                                                                                                                                                                                                                                                                                                                                                                                                                    PAYLOAD=$(cat <<EOF
                                                                                                                                                                                                                                                                                                                                                                                                                    {
                                                                                                                                                                                                                                                                                                                                                                                                                    "username": "Moodle Monitor",
                                                                                                                                                                                                                                                                                                                                                                                                                    "avatar_url": "https://moodle.org/theme/moodleorgsite/pix/moodle-logo.png",
                                                                                                                                                                                                                                                                                                                                                                                                                    "embeds": [{
                                                                                                                                                                                                                                                                                                                                                                                                                        "title": "${TITLE}",
                                                                                                                                                                                                                                                                                                                                                                                                                        "description": "${MESSAGE}",
                                                                                                                                                                                                                                                                                                                                                                                                                        "color": ${COLOR},
                                                                                                                                                                                                                                                                                                                                                                                                                        "footer": {
                                                                                                                                                                                                                                                                                                                                                                                                                        "text": "Host: ${HOSTNAME} | Env: ${ENVIRONMENT}"
                                                                                                                                                                                                                                                                                                                                                                                                                        },
                                                                                                                                                                                                                                                                                                                                                                                                                        "timestamp": "${TIMESTAMP}"
                                                                                                                                                                                                                                                                                                                                                                                                                    }]
                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                    EOF
                                                                                                                                                                                                                                                                                                                                                                                                                    )

                                                                                                                                                                                                                                                                                                                                                                                                                    curl -s -o /dev/null -w "%{http_code}" \
                                                                                                                                                                                                                                                                                                                                                                                                                        -H "Content-Type: application/json" \
                                                                                                                                                                                                                                                                                                                                                                                                                        -d "$PAYLOAD" \
                                                                                                                                                                                                                                                                                                                                                                                                                        "$WEBHOOK_URL" > /tmp/discord_response 2>&1

                                                                                                                                                                                                                                                                                                                                                                                                                    HTTP_CODE=$(cat /tmp/discord_response)
                                                                                                                                                                                                                                                                                                                                                                                                                    if [ "$HTTP_CODE" != "204" ]; then
                                                                                                                                                                                                                                                                                                                                                                                                                        echo "[$(date)] WARNING: Discord notification gagal (HTTP $HTTP_CODE)" >&2
                                                                                                                                                                                                                                                                                                                                                                                                                    fi