name: Release version

on:
  push:
    tags: 
      - "v*"

env:
  IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/moodle
  VERSION: ${{ github.ref_name }}

jobs:
  release:

    runs-on: ubuntu-latest

    permissions:
        contents: read
        packages: write
    
    steps:
      
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Production Image
        run: |
          docker build \
          --target production \
          -t $IMAGE_NAME:$VERSION \
          -t $IMAGE_NAME:latest .
      
      - name: Push image
        run: |
          docker push $IMAGE_NAME:$VERSION
          docker push $IMAGE_NAME:latest

      - name: Connect Tailscale
        uses: tailscale/github-action@v2
        with:
          authkey: ${{ secrets.TAILSCALE_AUTHKEY }}

      - name: Deploy to server
        uses: appleboy/ssh-action@v1.0.3
        with:
          #host: ${{ secrets.SERVER_HOST }}
          #username: ${{ secrets.SERVER_USER }}
          host: 100.111.65.26
          username: taufi
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd C:\moodle

            echo "Login GHCR"
            docker login ghcr.io -u taufiqr -p ${{ secrets.GHCR_TOKEN }}
            
            echo "Pull New Image"
            docker compose -f docker-compose.prod.yml pull
            

            echo "Restart Container"
            docker compose -f docker-compose.prod.yml up -d --remove-orphans

            echo "Cleanup Old Image"
            docker image prune -f